import react, { reactCompilerPreset } from '@vitejs/plugin-react'
import babel from '@rolldown/plugin-babel'
import { createHash } from 'node:crypto'
import { createReadStream, readFileSync } from 'node:fs'
import { stat } from 'node:fs/promises'
import path from 'node:path'
import { defineConfig, type Plugin } from 'vite'

import tailwindcss from '@tailwindcss/vite'

function sendMissing(
  response: { statusCode: number; setHeader(name: string, value: string): void; end(body: string): void },
  relativePath: string,
) {
  // Vite's HTML fallback would cache as a "successful" config fetch and break reload().
  response.statusCode = 404
  response.setHeader('Content-Type', 'application/json')
  response.end(JSON.stringify({ error: 'Model artifact not found', path: relativePath }))
}

function serveModels(): Plugin {
  const modelsRoot = path.resolve(import.meta.dirname, 'models')

  return {
    name: 'serve-local-webllm-models',
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        if (request.method !== 'GET' || !request.url?.startsWith('/models/')) {
          next()
          return
        }

        let filePath: string
        let relativePath: string
        try {
          const pathname = decodeURIComponent(new URL(request.url, 'http://localhost').pathname)
          relativePath = pathname
            .slice('/models/'.length)
            .replace('/resolve/main/', '/')
          filePath = path.resolve(modelsRoot, relativePath)
        } catch {
          response.statusCode = 400
          response.end('Invalid model path')
          return
        }

        // The mirror contains multi-gigabyte weights, so stream from outside public/ rather
        // than letting every Vite build copy the directory into dist.
        if (!filePath.startsWith(`${modelsRoot}${path.sep}`)) {
          response.statusCode = 403
          response.end('Model path escapes the mirror')
          return
        }

        void stat(filePath)
          .then((info) => {
            if (!info.isFile()) {
              sendMissing(response, relativePath)
              return
            }

            response.setHeader('Content-Length', info.size)
            response.setHeader(
              'Content-Type',
              filePath.endsWith('.wasm')
                ? 'application/wasm'
                : filePath.endsWith('.json')
                  ? 'application/json'
                  : 'application/octet-stream',
            )
            createReadStream(filePath).pipe(response)
          })
          .catch(() => sendMissing(response, relativePath))
      })
    },
  }
}

// Google Analytics, injected into the built index.html and nowhere else.
//
// The id comes from the build environment — Cloudflare Workers Builds exposes project variables
// to the build command as plain env vars, so `GA_MEASUREMENT_ID` needs no VITE_ prefix to be readable
// here (the prefixed name is accepted too, for a local `.env`). Without it the build emits no
// tag, no request to googletagmanager.com, and no third-party script: dev, `vite preview` and
// any deploy that has not set the variable are all analytics-free by construction.
//
// The shape is validated before it reaches the HTML. An id arrives as a build-time string from
// the deploy dashboard, and interpolating an unchecked one into an inline <script> would make
// that dashboard field an HTML injection point.
function analytics(): Plugin {
  const id = (process.env.GA_MEASUREMENT_ID ?? process.env.VITE_GA_MEASUREMENT_ID ?? '').trim()
  const valid = /^G-[A-Z0-9]{4,24}$/i.test(id)

  return {
    name: 'mote-analytics',
    apply: 'build',
    transformIndexHtml() {
      if (!valid) {
        if (id) this.warn(`GA_MEASUREMENT_ID "${id}" is not a G-XXXXXXXXXX id; no tag was injected`)
        return
      }

      return [
        {
          tag: 'script',
          attrs: { async: true, src: `https://www.googletagmanager.com/gtag/js?id=${id}` },
          injectTo: 'head',
        },
        {
          tag: 'script',
          children:
            'window.dataLayer=window.dataLayer||[];' +
            'function gtag(){dataLayer.push(arguments)}' +
            'gtag("js",new Date());' +
            `gtag("config",${JSON.stringify(id)});`,
          injectTo: 'head',
        },
      ]
    },
  }
}

// Emits dist/sw.js from src/sw.js with a real precache manifest.
//
// The worker is written by hand rather than generated by a plugin because its job here is
// mostly deciding what *not* to touch — the weight fetches, the model mirror — and a generated
// worker with a broad runtime-caching rule is exactly the wrong default in front of a 4 GB
// download. All the build has to contribute is the list of hashed files, which only it knows.
//
// Fonts and images are deliberately left out of the precache: seven Inter subsets ship, the
// browser fetches one, and the rest would be downloaded on install for nothing. They land in
// the runtime cache on first use instead.
function serviceWorker(): Plugin {
  const source = new URL('./src/sw.js', import.meta.url)
  const PRECACHE_EXTENSIONS = /\.(?:js|css)$/

  return {
    name: 'mote-service-worker',
    apply: 'build',
    // Runs last on purpose: index.html is emitted by Vite's own HTML plugin during
    // generateBundle, so a normally ordered plugin sees a bundle that has no HTML in it yet.
    enforce: 'post',
    generateBundle(_options, bundle) {
      const emitted = Object.keys(bundle)
        .filter((fileName) => PRECACHE_EXTENSIONS.test(fileName))
        .map((fileName) => `/${fileName}`)

      const precache = ['/index.html', '/manifest.webmanifest', '/favicon.svg', ...emitted]

      // Content-addressed, so a rebuild that changes nothing keeps its caches and a deploy
      // that changes something rotates them without a version number to remember. The asset
      // names carry their own content hash, which is why hashing the list is enough for them —
      // index.html is the one precached file whose name never changes, so it is hashed by its
      // bytes. Without that, adding a meta tag would ship a byte-identical sw.js, and a
      // byte-identical worker is one Chrome never installs.
      const html = bundle['index.html']
      const buildId = createHash('sha256')
        .update(precache.join('\n'))
        .update(html && html.type === 'asset' ? html.source : '')
        .digest('hex')
        .slice(0, 12)

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: readFileSync(source, 'utf8')
          .replace('"__BUILD_ID__"', JSON.stringify(buildId))
          .replace('["__PRECACHE__"]', JSON.stringify(precache, null, 2)),
      })
    },
  }
}

const { version } = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')) as {
  version: string
}

// https://vite.dev/config/
export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(version),
  },
  plugins: [
    serveModels(),
    analytics(),
    serviceWorker(),
    tailwindcss(),
    react(),
    babel({ presets: [reactCompilerPreset()] })
  ],
  resolve: {
    alias: {
      '@': path.resolve(import.meta.dirname, './src'),
    },
  },
  server: {
    watch: {
      // The CDP harness keeps its Chrome profile inside the repo and Chrome writes to it
      // constantly; without this, every write is a full page reload in the middle of a run.
      // The model mirror is multi-GB and never imported.
      ignored: ['**/.cdp-profile/**', '**/models/**'],
    },
  },
})
